Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,39 +1,47 @@
 name: CI Pipeline
+
 on:
   push:
     branches:
       - main
+
 jobs:
   RunMake:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
-        uses: actions/cheсkout@v4
+        uses: actions/checkout@v4
+
       - name: Install dependencies
-        run: sudo apt update && sudo apt install -y build-essential dpkg
+        run: sudo apt update && sudo apt install -y build-essential dpkg-dev
+
       - name: Run Make
         run: |
           cd src
           make || { echo "Make failed"; exit 1; }
           ls -l
           mkdir -p ../artifacts
-          cp ../usr/bin/main ../artifacts/ || { echo "Failed to copy main to artifacts"; exit 1; }
+          cp main ../artifacts/ || { echo "Failed to copy main to artifacts"; exit 1; }
+
       - name: Upload Artifact (Binary)
         uses: actions/upload-artifact@v4
         with:
           name: main-binary
           path: artifacts/
+
   RunTest:
     needs: RunMake
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
-        uses: actions/cheсkout@v4
+        uses: actions/checkout@v4
+
       - name: Download Artifact
         uses: actions/download-artifact@v4
         with:
           name: main-binary
           path: artifacts/
+
       - name: Run Tests
         run: |
           chmod +x artifacts/main
@@ -43,17 +51,20 @@ jobs:
           ./artifacts/main 5
           echo "Run with argument 6"
           ./artifacts/main 6
+
   RunPackage:
     needs: RunTest
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
-        uses: actions/cheсkout@v4
+        uses: actions/checkout@v4
+
       - name: Download Artifact
         uses: actions/download-artifact@v4
         with:
           name: main-binary
           path: artifacts/
+
       - name: Create Debian Package
         run: |
           mkdir -p artifacts/deb/usr/local/bin
@@ -61,6 +72,7 @@ jobs:
           cp DEBIAN/control artifacts/deb/DEBIAN
           cp artifacts/main artifacts/deb/usr/local/bin
           dpkg-deb --build artifacts/deb lab2.deb
+
       - name: Upload Debian Package
         uses: actions/upload-artifact@v4
         with:
